name       : telepathy-morse
version    : 0.1.0
release    : 3
source     :
    - https://github.com/TelepathyIM/telepathy-morse/archive/telepathy-morse-0.1.0.tar.gz : c9c361ef965b176a43e05d204eff7d83e508f4fcc3fd842c32a57187a3c7ce8f
license    : GPL-2.0-only
component  : network.im
summary    : Telepathy Connection Manager for Telegram network
description: |
    Telepathy Connection Manager for Telegram network
builddeps  :
    - pkgconfig(TelepathyQt5)
    - telegram-qt-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
